version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: start_prod
    restart: "always"
    ports:
      - '127.0.0.1:${APP_PORT:-3000}:3000'
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6
    restart: "always"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - ./volumes/mongodb:/data/db
    ports:
      - '127.0.0.1:${MONGO_PORT:-27017}:27017'

  redis:
    image: redis
    restart: always
    volumes:
      - ./volumes/redis:/data
